/**
 * Zuordnung deutscher Zutaten zu Lebensmitteln der USDA-Datenbank.
 *
 * Jeder Eintrag: [id, Anzeigename, SR-Beschreibung (genau), Stichwoerter,
 * Gewichtsangaben]. Die Naehrwerte selbst stehen hier bewusst nicht — sie
 * kommen beim Bauen aus der Datenbank, damit jede Zahl auf ihre Quelle
 * zurueckgeht. Hier wird nur entschieden, welches Lebensmittel gemeint ist.
 *
 * Stichwoerter folgen der Suche aus src/state/matcher.js: Treffer am
 * Wortanfang oder -ende, "=" fuer ein eigenstaendiges Wort, "~" fuer
 * einen Treffer auch mitten im Wort; das laengste Stichwort gewinnt.
 *
 * Gewichte (Gramm), wo die Datenbank keine passende Portion kennt oder
 * deutsche Groessen abweichen:
 *   stueck  ein Stueck, eine Frucht, ein Ei
 *   el, tl  ein gestrichener Ess- beziehungsweise Teeloeffel
 *   dichte  Gramm je Milliliter, fuer ml und l
 *   bund, zehe, scheibe, dose, becher, pck, blatt, zweig
 *   verzehr Anteil, der tatsaechlich gegessen wird (Frittieroel)
 */

export const ZUORDNUNG = [
  // ------------------------------------------------------------ Getreide, Backen
  ['weizenmehl', 'Weizenmehl', 'Wheat flour, white, all-purpose, enriched, bleached',
    ['mehl', 'weizenmehl', 'kuchenmehl', 'mehl type', 'stärkemehl'], {}],
  ['vollkornmehl', 'Weizenvollkornmehl', "Wheat flour, whole-grain (Includes foods for USDA's Food Distribution Program)",
    ['vollkornmehl', 'weizenvollkornmehl', 'vollkornweizenmehl', 'weizenschrot', 'backschrot'], {}],
  ['roggenmehl', 'Roggenmehl', 'Rye flour, medium', ['roggenmehl', 'roggenschrot'], {}],
  ['dinkelmehl', 'Dinkelmehl', 'Spelt, uncooked', ['dinkelmehl', 'dinkel'], {}],
  ['maismehl', 'Maismehl, Polenta', 'Cornmeal, whole-grain, yellow',
    ['maismehl', 'maisgrieß', 'polenta'], {}],
  ['griess', 'Grieß', 'Semolina, enriched', ['grieß', 'hartweizengrieß', 'weichweizengrieß', 'couscous'], {}],
  ['staerke', 'Speisestärke', 'Cornstarch', ['speisestärke', 'maisstärke', 'stärke', 'kartoffelstärke', 'mondamin'], {}],
  ['haferflocken', 'Haferflocken', 'Cereals, oats, regular and quick, not fortified, dry',
    ['haferflocken', 'hafer'], {}],
  ['reis', 'Reis', 'Rice, white, long-grain, regular, raw, enriched',
    ['reis', 'basmatireis', 'langkornreis', 'jasminreis', 'reisnudeln'], {}],
  ['rundkornreis', 'Rundkornreis', 'Rice, white, short-grain, enriched, uncooked',
    ['rundkornreis', 'milchreis', 'risottoreis', 'arborio', 'sushireis', 'klebreis'], {}],
  ['nudeln', 'Nudeln', 'Pasta, dry, enriched',
    ['nudel', 'nudeln', 'spaghetti', 'makkaroni', 'penne', 'tagliatelle', 'fusilli', 'farfalle',
      'lasagneplatten', 'bandnudeln', 'hörnchennudeln', 'glasnudeln', 'mie-nudeln', 'mienudeln'], {}],
  ['semmelbroesel', 'Semmelbrösel', 'Bread, crumbs, dry, grated, plain',
    ['semmelbrösel', 'brösel', 'paniermehl', 'weißbrotbrösel'], {}],
  ['weissbrot', 'Weißbrot, Toast', 'Bread, white, commercially prepared (includes soft bread crumbs)',
    ['weißbrot', 'toast', 'toastbrot', 'baguette', 'ciabatta', 'kastenweißbrot'], { scheibe: 25 }],
  ['broetchen', 'Brötchen', 'Rolls, hard (includes kaiser)',
    ['brötchen', 'semmel', 'semmeln', 'wecken', 'schrippe'], { stueck: 57 }],
  ['roggenbrot', 'Roggen- und Mischbrot', 'Bread, rye',
    ['roggenbrot', 'mischbrot', 'bauernbrot', 'graubrot', 'schwarzbrot', 'brot', 'sauerteigbrot'],
    { scheibe: 45 }],
  ['vollkornbrot', 'Vollkornbrot', 'Bread, whole-wheat, commercially prepared',
    ['vollkornbrot', 'pumpernickel'], { scheibe: 45 }],
  ['blaetterteig', 'Blätterteig', 'Puff pastry, frozen, ready-to-bake',
    ['blätterteig', 'puff-paste'], { scheibe: 75, pck: 275 }],
  ['loeffelbiskuit', 'Löffelbiskuits', 'Cookies, ladyfingers, with lemon juice and rind',
    ['löffelbiskuit', 'löffelbiskuits', 'biskotten'], { stueck: 11 }],

  // ------------------------------------------------------------ Zucker, Süßes
  ['zucker', 'Zucker', 'Sugars, granulated',
    ['zucker', 'kristallzucker', 'feinkristallzucker', 'vanillezucker', 'vanillinzucker',
      'hagelzucker', 'würfelzucker', 'gelierzucker', 'einmachzucker', 'raffinade'],
    { pck: 8 }],
  ['brauner_zucker', 'Brauner Zucker', 'Sugars, brown',
    ['brauner zucker', 'rohrzucker', 'farinzucker', 'weißer farinzucker', 'palmzucker',
      'kandiszucker', 'vollrohrzucker', 'muscovado'], {}],
  ['puderzucker', 'Puderzucker', 'Sugars, powdered', ['puderzucker', 'staubzucker'], {}],
  ['honig', 'Honig', 'Honey', ['honig'], {}],
  ['ahornsirup', 'Ahornsirup', 'Syrups, maple', ['ahornsirup'], {}],
  ['melasse', 'Melasse, Rübensirup', 'Molasses',
    ['melasse', 'zuckerrübensirup', 'rübensirup', 'rübenkraut', 'apfelkraut', 'birnenkraut'], {}],
  ['marmelade', 'Konfitüre', 'Jams and preserves',
    ['marmelade', 'konfitüre', 'aprikosenmarmelade', 'gelee', 'powidl'], {}],
  ['kakao', 'Kakaopulver', 'Cocoa, dry powder, unsweetened', ['kakao', 'kakaopulver', 'backkakao'], {}],
  ['zartbitter', 'Zartbitterschokolade', 'Chocolate, dark, 70-85% cacao solids',
    ['schokolade', 'zartbitterschokolade', 'zartbitter', 'kuvertüre', 'bitterschokolade',
      'raspelschokolade', 'schokoladenglasur', 'moccaschokolade'], {}],
  ['milchschokolade', 'Vollmilchschokolade', 'Candies, milk chocolate',
    ['milchschokolade', 'vollmilchschokolade', 'vollmilch-schokolade', 'vollmilch kuvertüre',
      'vollmich kuvertüre', 'kuvertüre (typ vollmilch)'], {}],
  ['weisse_schokolade', 'Weiße Schokolade', 'Candies, white chocolate', ['weiße schokolade'], {}],
  ['marzipan', 'Marzipan', 'Nuts, almond paste', ['marzipan', 'marzipan-rohmasse', 'persipan'], {}],
  ['nougat', 'Nuss-Nougat', 'Chocolate-flavored hazelnut spread',
    ['nougat', 'nuss-nougat', 'nuss-nougat-creme'], {}],
  ['rosinen', 'Rosinen', "Raisins, dark, seedless (Includes foods for USDA's Food Distribution Program)", ['rosinen', 'sultaninen', 'korinthen', 'rumrosinen'], {}],
  ['orangeat', 'Orangeat, Zitronat', 'Candied fruit', ['orangeat', 'zitronat', 'belegkirschen'], {}],
  ['gelatine', 'Gelatine', 'Gelatins, dry powder, unsweetened', ['gelatine', 'blattgelatine'],
    { blatt: 1.7, pck: 9 }],
  ['puddingpulver', 'Puddingpulver', 'Puddings, vanilla, dry mix, regular',
    ['puddingpulver', 'vanillepuddingpulver', 'custardpulver'], { pck: 37 }],

  // ------------------------------------------------------------ Triebmittel
  ['backpulver', 'Backpulver', 'Leavening agents, baking powder, double-acting, sodium aluminum sulfate',
    ['backpulver', 'weinsteinbackpulver'], { pck: 15 }],
  ['natron', 'Natron', 'Leavening agents, baking soda', ['natron', 'hirschhornsalz', 'pottasche'], { pck: 5 }],
  ['hefe', 'Frischhefe', "Leavening agents, yeast, baker's, compressed",
    ['hefe', 'frischhefe', 'germ', 'würfel hefe', 'hefewürfel'], { stueck: 42, pck: 42 }],
  ['trockenhefe', 'Trockenhefe', "Leavening agents, yeast, baker's, active dry", ['trockenhefe'], { pck: 7 }],

  // ------------------------------------------------------------ Fette, Öle
  ['butter', 'Butter', 'Butter, without salt',
    ['butter', 'butterflocken', 'süßrahmbutter', 'sauerrahmbutter', 'markenbutter'], {}],
  ['butterschmalz', 'Butterschmalz, Ghee', 'Butter, Clarified butter (ghee)',
    ['butterschmalz', 'ghee', 'butterreinfett'], {}],
  ['margarine', 'Margarine', 'Margarine, regular, 80% fat, composite, stick, with salt',
    ['margarine', 'pflanzenmargarine', 'sonnenblumenmargarine'], {}],
  ['schmalz', 'Schweineschmalz', 'Lard', ['schmalz', 'schweineschmalz', 'gänseschmalz'], {}],
  ['olivenoel', 'Olivenöl', 'Oil, olive, salad or cooking', ['olivenöl', 'olivenöl extra vergine'], {}],
  ['rapsoel', 'Pflanzenöl', 'Oil, canola',
    ['öl', 'rapsöl', 'pflanzenöl', 'speiseöl', 'sonnenblumenöl', 'maiskeimöl', 'distelöl',
      'bratöl', 'neutrales öl', 'traubenkernöl', 'sojaöl'], {}],
  ['frittieroel', 'Frittieröl (nur aufgenommener Anteil)', 'Oil, canola',
    ['frittieröl', 'öl zum frittieren', 'fett zum frittieren', 'öl zum ausbacken',
      'fett zum ausbacken', 'frittierfett', 'öl zum braten'], { verzehr: 0.1 }],
  ['erdnussoel', 'Erdnussöl', 'Oil, peanut, salad or cooking', ['erdnussöl'], {}],
  ['sesamoel', 'Sesamöl', 'Oil, sesame, salad or cooking', ['sesamöl'], {}],
  ['kokosoel', 'Kokosöl', 'Oil, coconut', ['kokosöl', 'kokosfett', 'kokosnussöl', 'palmin'], {}],
  ['walnussoel', 'Walnussöl', 'Oil, walnut', ['walnussöl', 'haselnussöl'], {}],

  // ------------------------------------------------------------ Milch, Käse, Eier
  ['milch', 'Vollmilch', 'Milk, whole, 3.25% milkfat, with added vitamin D',
    ['milch', 'vollmilch', 'frischmilch', 'kuhmilch'], {}],
  ['fettarme_milch', 'Fettarme Milch', 'Milk, lowfat, fluid, 1% milkfat, with added vitamin A and vitamin D',
    ['fettarme milch', 'magermilch', 'entrahmte milch', 'milch 1,5'], {}],
  ['buttermilch', 'Buttermilch', 'Milk, buttermilk, fluid, cultured, lowfat', ['buttermilch', 'dickmilch', 'kefir'], {}],
  ['kondensmilch', 'Gezuckerte Kondensmilch', 'Milk, canned, condensed, sweetened',
    ['gezuckerte kondensmilch', 'kondensmilch gezuckert', 'milchmädchen'], {}],
  ['kondensmilch_ungezuckert', 'Kondensmilch', 'Milk, canned, evaporated, with added vitamin D and without added vitamin A',
    ['kondensmilch', 'dosenmilch', 'kaffeesahne'], {}],
  ['sahne', 'Sahne', 'Cream, fluid, light whipping',
    ['sahne', 'schlagsahne', 'süße sahne', 'obers', 'schlagobers', 'rahm', 'kochsahne', 'cremefine'],
    // Die Datenbank misst Sahne nur geschlagen je Tasse — fluessig ist sie so dicht wie Milch.
    { dichte: 1.0 }],
  ['creme_fraiche', 'Crème fraîche', 'Cream, fluid, heavy whipping',
    ['crème fraîche', 'creme fraiche', 'crème double', 'clotted cream'], { dichte: 1.0 }],
  ['schmand', 'Schmand', 'Cream, sour, cultured', ['schmand', 'sauerrahm', 'saure sahne', 'smetana'], {}],
  ['joghurt', 'Joghurt', 'Yogurt, plain, whole milk',
    ['joghurt', 'naturjoghurt', 'griechischer joghurt', 'sahnejoghurt', 'jogurt'], { becher: 150 }],
  ['quark', 'Magerquark', 'Cheese, cottage, nonfat, uncreamed, dry, large or small curd',
    ['quark', 'magerquark', 'speisequark', 'topfen', 'skyr'], { dichte: 1.0, el: 15 }],
  ['frischkaese', 'Frischkäse', 'Cheese, cream',
    ['frischkäse', 'doppelrahmfrischkäse', 'mascarpone', 'philadelphia', 'hüttenkäse'], {}],
  ['parmesan', 'Parmesan', 'Cheese, parmesan, hard',
    ['parmesan', 'parmesankäse', 'grana padano', 'pecorino', 'parmigiano'], {}],
  ['hartkaese', 'Emmentaler, Bergkäse', 'Cheese, swiss',
    ['emmentaler', 'bergkäse', 'greyerzer', 'gruyère', 'appenzeller', 'hartkäse', 'käse',
      'reibekäse', 'raclettekäse', 'allgäuer'], { scheibe: 20 }],
  ['gouda', 'Gouda', 'Cheese, gouda', ['gouda', 'edamer', 'butterkäse', 'tilsiter'], { scheibe: 20 }],
  ['cheddar', 'Cheddar', "Cheese, cheddar (Includes foods for USDA's Food Distribution Program)", ['cheddar'], { scheibe: 20 }],
  ['feta', 'Feta', 'Cheese, feta', ['feta', 'schafskäse', 'hirtenkäse'], {}],
  ['mozzarella', 'Mozzarella', 'Cheese, mozzarella, whole milk', ['mozzarella', 'burrata'], { stueck: 125 }],
  ['ricotta', 'Ricotta', 'Cheese, ricotta, whole milk', ['ricotta'], {}],
  ['camembert', 'Camembert, Brie', 'Cheese, camembert', ['camembert', 'brie', 'weichkäse'], { stueck: 125 }],
  ['ziegenkaese', 'Ziegenkäse', 'Cheese, goat, soft type', ['ziegenkäse', 'ziegenfrischkäse', 'picandou'], {}],
  ['ei', 'Ei', 'Egg, whole, raw, fresh',
    ['=ei', 'eier', 'vollei', 'ganze eier', 'hühnerei', 'hühnereier'],
    // Deutsche Groesse M, ohne Schale; die Datenbank kennt nur US-Groessen.
    { stueck: 50 }],
  ['eigelb', 'Eigelb', 'Egg, yolk, raw, fresh', ['eigelb', 'eigelbe', 'eidotter', 'dotter'], {}],
  ['eiweiss', 'Eiweiß', 'Egg, white, raw, fresh', ['eiweiß', 'eiklar', 'eischnee'], { stueck: 33 }],

  // ------------------------------------------------------------ Fleisch
  ['rinderhack', 'Rinderhack', 'Beef, ground, 80% lean meat / 20% fat, raw',
    ['hackfleisch', 'rinderhack', 'rinderhackfleisch', 'gemischtes hackfleisch', 'gemischtes hack',
      'hack', 'faschiertes'], {}],
  ['schweinehack', 'Schweinehack, Mett', 'Pork, fresh, ground, raw',
    ['schweinehack', 'schweinehackfleisch', 'mett', 'hackfleisch vom schwein', 'bratwurstbrät', 'brät'], {}],
  ['rindfleisch', 'Rindfleisch', 'Beef, chuck, arm pot roast, separable lean and fat, trimmed to 1/8" fat, all grades, raw',
    ['rindfleisch', 'rind', 'rinderbraten', 'gulasch', 'rindergulasch', 'schmorbraten', 'tafelspitz',
      'beinscheibe', 'suppenfleisch', 'rinderschulter', 'ochsenfleisch', 'rinderwade'], {}],
  ['rindersteak', 'Rindersteak, Filet', 'Beef, top sirloin, steak, separable lean and fat, trimmed to 1/8" fat, all grades, raw',
    ['steak', 'rumpsteak', 'rinderfilet', 'roastbeef', 'entrecote', 'hüftsteak', 'rouladen', 'roulade'], { stueck: 200 }],
  ['schweinefleisch', 'Schweinefleisch', 'Pork, fresh, shoulder, whole, separable lean and fat, raw',
    ['schweinefleisch', 'schwein', 'schweinebraten', 'schweineschulter', 'schweinenacken',
      'nacken', 'kotelett', 'schweinekotelett', 'schnitzel', 'schweineschnitzel', 'kasseler',
      'schweinegulasch', 'eisbein', 'schweinshaxe', 'schäufele'], { stueck: 150 }],
  ['schweinefilet', 'Schweinefilet', 'Pork, fresh, loin, tenderloin, separable lean only, raw',
    ['schweinefilet', 'schweinelende', 'filet vom schwein'], { stueck: 400 }],
  ['schweinebauch', 'Schweinebauch', 'Pork, fresh, belly, raw', ['schweinebauch', 'bauchfleisch', 'wammerl'], {}],
  ['speck', 'Speck', 'Pork, cured, bacon, unprepared',
    ['speck', 'bacon', 'speckwürfel', 'frühstücksspeck', 'bauchspeck', 'durchwachsener speck',
      'schinkenspeck', 'pancetta', 'räucherspeck'], { scheibe: 12 }],
  ['kochschinken', 'Kochschinken', 'Ham, sliced, regular (approximately 11% fat)',
    ['schinken', 'kochschinken', 'gekochter schinken', 'schinkenwürfel'], { scheibe: 25 }],
  ['rohschinken', 'Roher Schinken', 'Pork, cured, ham, boneless, regular (approximately 11% fat), roasted',
    ['roher schinken', 'rohschinken', 'parmaschinken', 'serranoschinken', 'schwarzwälder schinken',
      'prosciutto', 'katenschinken'], { scheibe: 15 }],
  ['haehnchenbrust', 'Hähnchenbrust', 'Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw',
    ['hähnchenbrust', 'hähnchenbrustfilet', 'hühnerbrust', 'hühnerbrustfilet', 'hähnchenfilet',
      'hühnchenbrust', 'hähnchenfleisch', 'hühnerfleisch', 'hühnchenfleisch', 'geflügel'], { stueck: 150 }],
  ['haehnchen', 'Hähnchen mit Haut', 'Chicken, broilers or fryers, meat and skin, raw',
    ['hähnchen', 'hähnchenteile', 'hähnchenschenkel', 'hähnchenkeulen', 'huhn', 'hühnchen',
      'poularde', 'suppenhuhn', 'hühnerkeulen', 'chicken wings', 'hähnchenflügel'], { stueck: 200 }],
  ['pute', 'Pute', 'Turkey, whole, breast, meat only, raw',
    ['pute', 'putenbrust', 'putenfleisch', 'putenschnitzel', 'truthahn'], { stueck: 150 }],
  ['lamm', 'Lammfleisch', 'Lamb, shoulder, whole (arm and blade), separable lean and fat, trimmed to 1/4" fat, choice, raw',
    ['lamm', 'lammfleisch', 'lammschulter', 'lammkeule', 'lammkotelett', 'hammel', 'lammhack'], { stueck: 80 }],
  ['kalb', 'Kalbfleisch', 'Veal, leg (top round), separable lean only, raw',
    ['kalb', 'kalbfleisch', 'kalbsschnitzel', 'kalbsbraten', 'kalbshaxe', 'kalbsnuss'], { stueck: 150 }],
  ['ente', 'Ente', 'Duck, domesticated, meat and skin, raw', ['ente', 'entenbrust', 'entenkeule', 'gans'], { stueck: 300 }],
  ['wild', 'Wild', 'Game meat, deer, raw', ['reh', 'hirsch', 'wild', 'rehrücken', 'hirschgulasch', 'wildschwein'], { stueck: 150 }],
  ['kaninchen', 'Kaninchen', 'Game meat, rabbit, domesticated, composite of cuts, raw', ['kaninchen', 'hase'], {}],
  ['bratwurst', 'Bratwurst', 'Bratwurst, pork, cooked',
    ['bratwurst', 'bratwürste', 'wurst', 'würstchen', 'wiener', 'frankfurter', 'bockwurst',
      'mettwurst', 'chorizo', 'rostbratwürste', 'weißwurst', 'krakauer'], { stueck: 100 }],
  ['salami', 'Salami', 'Salami, dry or hard, pork', ['salami', 'cabanossi', 'landjäger'], { scheibe: 5 }],
  ['leber', 'Leber', 'Beef, variety meats and by-products, liver, raw', ['leber', 'rinderleber', 'kalbsleber', 'schweineleber', 'geflügelleber', 'hühnerleber'], { stueck: 120 }],

  // ------------------------------------------------------------ Fisch, Meeresfrüchte
  ['kabeljau', 'Kabeljau, Seelachs', 'Fish, cod, Atlantic, raw',
    ['fisch', 'fischfilet', 'kabeljau', 'kabeljaufilet', 'dorsch', 'seelachs', 'seelachsfilet',
      'schellfisch', 'rotbarsch', 'zander', 'hecht', 'scholle', 'seezunge', 'weißfisch',
      'gemischter fisch', 'pangasius', 'heilbutt', 'wolfsbarsch', 'dorade', 'karpfen'], { stueck: 150 }],
  ['lachs', 'Lachs', 'Fish, salmon, Atlantic, farmed, raw', ['lachs', 'lachsfilet', 'wildlachs', 'saibling'], { stueck: 150 }],
  ['raeucherlachs', 'Räucherlachs', 'Fish, salmon, chinook, smoked', ['räucherlachs', 'geräucherter lachs', 'graved lachs'], {}],
  ['forelle', 'Forelle', 'Fish, trout, rainbow, farmed, raw', ['forelle', 'forellenfilet', 'räucherforelle'], { stueck: 250 }],
  ['thunfisch', 'Thunfisch (Dose)', 'Fish, tuna, light, canned in water, without salt, drained solids', ['thunfisch'], { dose: 150 }],
  ['hering', 'Hering', 'Fish, herring, Atlantic, raw', ['hering', 'heringsfilet', 'bismarckhering', 'brathering'], { stueck: 150 }],
  ['matjes', 'Matjes', 'Fish, herring, Atlantic, pickled', ['matjes', 'matjesfilet', 'rollmops'], { stueck: 50 }],
  ['makrele', 'Makrele', 'Fish, mackerel, Atlantic, raw', ['makrele', 'räuchermakrele', 'makrelenfilet'], { stueck: 200 }],
  ['aal', 'Aal', 'Fish, eel, mixed species, raw', ['aal', 'aale', 'aalfilet', 'aalfilets', 'räucheraal', 'suppenaal', 'suppenaale'], {}],
  ['sardellen', 'Sardellen', 'Fish, anchovy, european, canned in oil, drained solids',
    ['sardellen', 'sardellenfilet', 'sardellenfilets', 'anchovis', 'anchovisfilets', 'sardelle'], { stueck: 4 }],
  ['sardinen', 'Sardinen', 'Fish, sardine, Atlantic, canned in oil, drained solids with bone', ['sardinen', 'sardine'], { dose: 90 }],
  ['stockfisch', 'Stockfisch', 'Fish, cod, Atlantic, dried and salted', ['stockfisch', 'klippfisch', 'bacalhau', 'bakkeljauw'], {}],
  ['garnelen', 'Garnelen', 'Crustaceans, shrimp, raw',
    ['garnele', 'garnelen', 'shrimps', 'shrimp', 'scampi', 'krabben', 'nordseekrabben', 'gambas',
      'krebsfleisch', 'flusskrebsfleisch', 'flusskrebse', 'hummer', 'langusten', 'riesengarnelen'], {}],
  ['muscheln', 'Muscheln', 'Mollusks, mussel, blue, raw', ['muschel', 'muscheln', 'miesmuscheln', 'venusmuscheln', 'jakobsmuscheln'], {}],
  ['tintenfisch', 'Tintenfisch', 'Mollusks, squid, mixed species, raw', ['tintenfisch', 'tintenfischringe', 'kalmar', 'calamari', 'oktopus', 'sepia'], {}],

  // ------------------------------------------------------------ Gemüse
  ['kartoffeln', 'Kartoffeln', 'Potatoes, flesh and skin, raw',
    ['kartoffel', 'kartoffeln', 'erdäpfel', 'frühkartoffeln', 'pellkartoffeln', 'salzkartoffeln',
      'drillinge', 'grumbeere'], { stueck: 120 }],
  ['suesskartoffel', 'Süßkartoffel', "Sweet potato, raw, unprepared (Includes foods for USDA's Food Distribution Program)", ['süßkartoffel', 'süßkartoffeln', 'batate'], { stueck: 250 }],
  ['zwiebel', 'Zwiebel', 'Onions, raw',
    ['zwiebel', 'zwiebeln', 'gemüsezwiebel', 'rote zwiebel', 'rote zwiebeln', 'zwiebelringe', 'perlzwiebeln'], {}],
  ['schalotte', 'Schalotten', 'Shallots, raw', ['schalotte', 'schalotten'], { stueck: 25 }],
  ['fruehlingszwiebel', 'Frühlingszwiebeln', 'Onions, spring or scallions (includes tops and bulb), raw',
    ['frühlingszwiebel', 'frühlingszwiebeln', 'lauchzwiebel', 'lauchzwiebeln'], { stueck: 15, bund: 120 }],
  ['knoblauch', 'Knoblauch', 'Garlic, raw',
    ['knoblauch', 'knoblauchzehe', 'knoblauchzehen', 'knofi'], { stueck: 3, zehe: 3 }],
  ['moehren', 'Möhren', 'Carrots, raw',
    ['möhre', 'möhren', 'karotte', 'karotten', 'mohrrübe', 'mohrrüben', 'rüebli'], { stueck: 80 }],
  ['tomaten', 'Tomaten', 'Tomatoes, red, ripe, raw, year round average',
    ['tomate', 'tomaten', 'kirschtomaten', 'cocktailtomaten', 'strauchtomaten', 'fleischtomaten', 'eiertomaten', 'rispentomaten'],
    { stueck: 100 }],
  ['dosentomaten', 'Tomaten aus der Dose', 'Tomatoes, red, ripe, canned, packed in tomato juice',
    ['dosentomaten', 'geschälte tomaten', 'stückige tomaten', 'passierte tomaten', 'tomaten aus der dose',
      'pizzatomaten', 'passata', 'tomatenstücke'], { dose: 400 }],
  ['tomatenmark', 'Tomatenmark', "Tomato products, canned, paste, without salt added (Includes foods for USDA's Food Distribution Program)", ['tomatenmark', 'tomatenpüree'], {}],
  ['paprika', 'Paprikaschote', 'Peppers, sweet, red, raw',
    ['paprika', 'paprikaschote', 'paprikaschoten', 'rote paprika', 'gelbe paprika', 'spitzpaprika'], { stueck: 150 }],
  ['gruene_paprika', 'Grüne Paprika', 'Peppers, sweet, green, raw', ['grüne paprika', 'grüne paprikaschote'], { stueck: 150 }],
  ['chili', 'Chilischote', 'Peppers, hot chili, red, raw',
    ['chili', 'chilischote', 'chilischoten', 'peperoni', 'peperoncini', 'jalapeño', 'jalapeños', 'rote chilischoten'],
    { stueck: 10 }],
  ['zucchini', 'Zucchini', 'Squash, summer, zucchini, includes skin, raw', ['zucchini', 'zucchinis', 'zucchetti'], { stueck: 200 }],
  ['aubergine', 'Aubergine', 'Eggplant, raw', ['aubergine', 'auberginen', 'melanzani'], { stueck: 300 }],
  ['gurke', 'Salatgurke', 'Cucumber, with peel, raw', ['gurke', 'gurken', 'salatgurke', 'schlangengurke', 'minigurken'], { stueck: 300 }],
  ['gewuerzgurke', 'Gewürzgurken', 'Pickles, cucumber, dill or kosher dill',
    ['gewürzgurke', 'gewürzgurken', 'essiggurke', 'essiggurken', 'cornichons', 'senfgurken', 'saure gurken'], { stueck: 35 }],
  ['weisskohl', 'Weißkohl', 'Cabbage, raw',
    ['kohl', 'weißkohl', 'spitzkohl', 'wirsing', 'chinakohl', 'weißkraut', 'kraut', 'kohlkopf', 'pak choi'], { stueck: 1000, blatt: 30 }],
  ['rotkohl', 'Rotkohl', 'Cabbage, red, raw', ['rotkohl', 'blaukraut', 'rotkraut'], { stueck: 1000 }],
  ['sauerkraut', 'Sauerkraut', 'Sauerkraut, canned, solids and liquids', ['sauerkraut'], { dose: 500 }],
  ['lauch', 'Lauch', 'Leeks, (bulb and lower leaf-portion), raw', ['lauch', 'porree', 'stange lauch'], { stueck: 150 }],
  ['sellerieknolle', 'Knollensellerie', 'Celeriac, raw', ['sellerie', 'knollensellerie', 'sellerieknolle'], { stueck: 400 }],
  ['staudensellerie', 'Staudensellerie', 'Celery, raw',
    ['staudensellerie', 'stangensellerie', 'stangen sellerie', 'stange sellerie', 'bleichsellerie', 'selleriegrün'], { stueck: 40 }],
  ['suppengruen', 'Suppengrün', 'Carrots, raw', ['suppengrün', 'wurzelgemüse'], { bund: 350, pck: 350 }],
  ['spinat', 'Spinat', 'Spinach, raw', ['spinat', 'blattspinat', 'babyspinat', 'mangold'], {}],
  ['champignons', 'Champignons, Pilze', 'Mushrooms, white, raw',
    ['champignon', 'champignons', 'pilze', 'pilz', 'steinpilze', 'pfifferlinge', 'kräuterseitlinge',
      'austernpilze', 'egerlinge', 'shiitake', 'mischpilze', 'waldpilze', 'eierschwammerl'], { stueck: 18 }],
  ['erbsen', 'Erbsen', 'Peas, green, raw', ['erbsen', 'tk-erbsen', 'zuckerschoten', 'kaiserschoten'], {}],
  ['gruene_bohnen', 'Grüne Bohnen', 'Beans, snap, green, raw', ['grüne bohnen', 'brechbohnen', 'buschbohnen', 'stangenbohnen', 'prinzessbohnen', 'bohnen'], {}],
  ['weisse_bohnen', 'Weiße Bohnen (Dose)', 'Beans, white, mature seeds, canned',
    ['weiße bohnen', 'cannellini', 'cannellinibohnen', 'bohnenkerne', 'dicke bohnen', 'saubohnen', 'baked beans'], { dose: 250 }],
  ['kidneybohnen', 'Kidneybohnen (Dose)', 'Beans, kidney, red, mature seeds, canned, drained solids',
    ['kidneybohnen', 'rote bohnen', 'schwarze bohnen', 'pintobohnen'], { dose: 250 }],
  ['kichererbsen', 'Kichererbsen (Dose)', 'Chickpeas (garbanzo beans, bengal gram), mature seeds, canned, drained solids',
    ['kichererbsen'], { dose: 240 }],
  ['linsen', 'Linsen (trocken)', 'Lentils, raw',
    ['linsen', 'berglinsen', 'tellerlinsen', 'belugalinsen', 'schälerbsen', 'spalterbsen', 'gelbe erbsen'], {}],
  ['rote_linsen', 'Rote Linsen (trocken)', 'Lentils, pink or red, raw', ['rote linsen', 'gelbe linsen'], {}],
  ['mais', 'Mais (Dose)', 'Corn, sweet, yellow, canned, whole kernel, drained solids', ['mais', 'maiskörner', 'zuckermais'], { dose: 285 }],
  ['kuerbis', 'Kürbis', 'Pumpkin, raw', ['kürbis', 'hokkaido', 'butternut', 'butternutkürbis', 'muskatkürbis'], {}],
  ['rote_bete', 'Rote Bete', 'Beets, raw', ['rote bete', 'rote beete', 'rote rübe', 'rote rüben', 'randen'], { stueck: 150 }],
  ['brokkoli', 'Brokkoli', 'Broccoli, raw', ['brokkoli', 'broccoli', 'romanesco'], { stueck: 400 }],
  ['blumenkohl', 'Blumenkohl', 'Cauliflower, raw', ['blumenkohl', 'karfiol'], { stueck: 800 }],
  ['kohlrabi', 'Kohlrabi', 'Kohlrabi, raw', ['kohlrabi'], { stueck: 250 }],
  ['rosenkohl', 'Rosenkohl', 'Brussels sprouts, raw', ['rosenkohl', 'kohlsprossen'], {}],
  ['gruenkohl', 'Grünkohl', 'Kale, raw', ['grünkohl', 'palmkohl', 'federkohl'], {}],
  ['spargel', 'Spargel', 'Asparagus, raw', ['spargel', 'grüner spargel', 'weißer spargel'], { stueck: 20 }],
  ['fenchel', 'Fenchel', 'Fennel, bulb, raw', ['fenchel', 'fenchelknolle'], { stueck: 250 }],
  ['salat', 'Blattsalat', 'Lettuce, green leaf, raw',
    ['salat', 'blattsalat', 'kopfsalat', 'feldsalat', 'eisbergsalat', 'römersalat', 'lollo rosso',
      'friséesalat', 'endivie', 'endiviensalat', 'radicchio', 'chicorée', 'pflücksalat', 'rucola', 'rauke'], { stueck: 300 }],
  ['radieschen', 'Radieschen', 'Radishes, raw', ['radieschen', 'rettich', 'radi'], { bund: 150, stueck: 10 }],
  ['steckrueben', 'Steckrüben', 'Rutabagas, raw', ['steckrübe', 'steckrüben', 'kohlrübe', 'wruke'], {}],
  ['pastinaken', 'Pastinaken', 'Parsnips, raw', ['pastinake', 'pastinaken', 'petersilienwurzel', 'schwarzwurzeln', 'topinambur'], { stueck: 150 }],
  ['avocado', 'Avocado', 'Avocados, raw, all commercial varieties', ['avocado', 'avocados'], { stueck: 150 }],
  ['oliven', 'Oliven', 'Olives, ripe, canned (small-extra large)', ['oliven', 'olive', 'schwarze oliven', 'grüne oliven', 'kalamata'], { stueck: 4 }],
  ['ingwer', 'Ingwer', 'Ginger root, raw', ['ingwer', 'ingwerwurzel', 'frischer ingwer', 'galgant'], { stueck: 10 }],
  ['bambussprossen', 'Bambussprossen', 'Bamboo shoots, canned, drained solids', ['bambussprossen', 'sojasprossen', 'mungbohnensprossen'], {}],
  ['kraeuter', 'Frische Kräuter', 'Parsley, fresh',
    ['petersilie', 'glatte petersilie', 'krause petersilie', 'schnittlauch', 'basilikum', 'dill', 'kerbel',
      'koriandergrün', 'korianderblätter', 'frischer koriander', 'minze', 'pfefferminze', 'bärlauch',
      'kräuter', 'estragon', 'liebstöckel', 'zitronenmelisse', 'kresse', 'brunnenkresse', 'zitronengras'],
    { bund: 30, zweig: 2, blatt: 0.5, el: 4, tl: 1.3 }],

  // ------------------------------------------------------------ Obst
  ['aepfel', 'Äpfel', "Apples, raw, with skin (Includes foods for USDA's Food Distribution Program)",
    ['apfel', 'äpfel', 'boskoop', 'boskoopäpfel', 'elstar', 'säuerliche äpfel', 'kochäpfel', 'backäpfel'], { stueck: 150 }],
  ['birnen', 'Birnen', 'Pears, raw', ['birne', 'birnen'], { stueck: 170 }],
  ['bananen', 'Bananen', 'Bananas, raw', ['banane', 'bananen', 'reife bananen'], { stueck: 115 }],
  ['zitrone', 'Zitrone', 'Lemons, raw, without peel', ['zitrone', 'zitronen', 'bio-zitrone', 'unbehandelte zitrone'], { stueck: 60 }],
  ['zitronensaft', 'Zitronensaft', 'Lemon juice, raw', ['zitronensaft', 'saft einer zitrone', 'saft von 1 zitrone'], {}],
  ['zitronenschale', 'Zitronenschale', 'Lemon peel, raw',
    ['zitronenschale', 'zitronenabrieb', 'abrieb', 'orangenschale', 'orangenabrieb', 'limettenschale', 'limettenabrieb'], { stueck: 6 }],
  ['limette', 'Limette', 'Limes, raw', ['limette', 'limetten'], { stueck: 65 }],
  ['limettensaft', 'Limettensaft', 'Lime juice, raw', ['limettensaft'], {}],
  ['orange', 'Orange', 'Oranges, raw, all commercial varieties', ['orange', 'orangen', 'apfelsine', 'mandarine', 'mandarinen', 'clementine', 'blutorange'], { stueck: 130 }],
  ['orangensaft', 'Orangensaft', "Orange juice, raw (Includes foods for USDA's Food Distribution Program)", ['orangensaft', 'o-saft'], {}],
  ['apfelsaft', 'Apfelsaft', 'Apple juice, canned or bottled, unsweetened, without added ascorbic acid',
    ['apfelsaft', 'apfelmost', 'traubensaft', 'most', 'cidre'], {}],
  ['ananas', 'Ananas', 'Pineapple, raw, all varieties', ['ananas', 'ananasscheiben', 'ananasstücke'], { stueck: 900, scheibe: 55 }],
  ['aprikosen', 'Aprikosen', 'Apricots, raw', ['aprikose', 'aprikosen', 'marillen', 'pfirsich', 'pfirsiche', 'nektarine', 'nektarinen'], { stueck: 40 }],
  ['trockenaprikosen', 'Getrocknete Aprikosen', 'Apricots, dried, sulfured, uncooked',
    ['getrocknete aprikosen', 'trockenaprikosen', 'soft-aprikosen', 'trockenobst', 'dörrobst'], { stueck: 8 }],
  ['pflaumen', 'Pflaumen', 'Plums, raw', ['pflaume', 'pflaumen', 'zwetschge', 'zwetschgen', 'zwetschken', 'mirabellen'], { stueck: 40 }],
  ['backpflaumen', 'Backpflaumen', 'Plums, dried (prunes), uncooked', ['backpflaumen', 'trockenpflaumen', 'dörrpflaumen'], { stueck: 10 }],
  ['kirschen', 'Kirschen', 'Cherries, sweet, raw', ['kirschen', 'süßkirschen', 'sauerkirschen', 'schattenmorellen', 'amarenakirschen'], {}],
  ['erdbeeren', 'Erdbeeren', 'Strawberries, raw', ['erdbeeren', 'erdbeere'], {}],
  ['beeren', 'Beeren', 'Raspberries, raw',
    ['himbeeren', 'beeren', 'brombeeren', 'johannisbeeren', 'stachelbeeren', 'heidelbeeren', 'blaubeeren',
      'preiselbeeren', 'cranberries', 'waldbeeren', 'beerenmischung'], {}],
  ['rhabarber', 'Rhabarber', 'Rhubarb, raw', ['rhabarber'], { stueck: 100 }],
  ['mango', 'Mango', 'Mangos, raw', ['mango', 'mangos'], { stueck: 300 }],
  ['trauben', 'Weintrauben', 'Grapes, red or green (European type, such as Thompson seedless), raw', ['trauben', 'weintrauben', 'weinbeeren'], {}],
  ['feigen', 'Feigen', 'Figs, raw', ['feige', 'feigen'], { stueck: 50 }],
  ['datteln', 'Datteln', 'Dates, medjool', ['dattel', 'datteln'], { stueck: 20 }],
  ['quitten', 'Quitten', 'Quinces, raw', ['quitte', 'quitten'], { stueck: 250 }],
  ['kokosraspel', 'Kokosraspeln', 'Nuts, coconut meat, dried (desiccated), not sweetened', ['kokosraspel', 'kokosraspeln', 'kokosflocken'], {}],
  ['kokosmilch', 'Kokosmilch', 'Nuts, coconut milk, canned (liquid expressed from grated meat and water)',
    ['kokosmilch', 'kokoscreme', 'kokosnussmilch'], { dose: 400 }],

  // ------------------------------------------------------------ Nüsse, Samen
  ['mandeln', 'Mandeln', 'Nuts, almonds',
    ['mandel', 'mandeln', 'mandelblättchen', 'mandelstifte', 'gemahlene mandeln', 'mandelmehl', 'bittermandel'], {}],
  ['haselnuesse', 'Haselnüsse', 'Nuts, hazelnuts or filberts',
    ['haselnuss', 'haselnüsse', 'haselnusskerne', 'haselnussblättchen', 'haselnuss-krokant', 'krokant', 'nüsse', 'nuss', 'nusskerne', 'kemirinüsse'], {}],
  ['walnuesse', 'Walnüsse', 'Nuts, walnuts, english', ['walnuss', 'walnüsse', 'walnusskerne', 'walnusshälften', 'pekannüsse', 'pekannuss'], {}],
  ['pinienkerne', 'Pinienkerne', 'Nuts, pine nuts, dried', ['pinienkerne'], {}],
  ['cashew', 'Cashewkerne', 'Nuts, cashew nuts, raw', ['cashew', 'cashewkerne', 'cashewnüsse'], {}],
  ['pistazien', 'Pistazien', 'Nuts, pistachio nuts, raw', ['pistazie', 'pistazien', 'pistazienkerne'], {}],
  ['erdnuesse', 'Erdnüsse', 'Peanuts, all types, raw', ['erdnuss', 'erdnüsse', 'erdnusskerne'], {}],
  ['erdnussbutter', 'Erdnussbutter', 'Peanut butter, smooth style, without salt', ['erdnussbutter', 'erdnusscreme', 'erdnussmus'], {}],
  ['sesam', 'Sesam', 'Seeds, sesame seeds, whole, dried', ['sesam', 'sesamsamen', 'sesamkörner', 'sesamsaat'], {}],
  ['tahin', 'Tahin', 'Seeds, sesame butter, tahini, from roasted and toasted kernels (most common type)', ['tahin', 'tahini', 'sesampaste'], {}],
  ['sonnenblumenkerne', 'Sonnenblumenkerne', 'Seeds, sunflower seed kernels, dried', ['sonnenblumenkerne'], {}],
  ['kuerbiskerne', 'Kürbiskerne', 'Seeds, pumpkin and squash seed kernels, dried', ['kürbiskerne'], {}],
  ['leinsamen', 'Leinsamen', 'Seeds, flaxseed', ['leinsamen', 'chiasamen', 'chia'], {}],
  ['mohn', 'Mohn', 'Spices, poppy seed', ['mohn', 'blaumohn', 'mohnsamen'], {}],

  // ------------------------------------------------------------ Gewürze
  ['salz', 'Salz', 'Salt, table',
    ['salz', 'meersalz', 'speisesalz', 'jodsalz', 'kräutersalz', 'fleur de sel', 'steinsalz', 'pökelsalz', 'selleriesalz'], { tl: 6, el: 18 }],
  ['pfeffer', 'Pfeffer', 'Spices, pepper, black',
    ['pfeffer', 'schwarzer pfeffer', 'weißer pfeffer', 'pfefferkörner', 'pfeffer aus der mühle', 'grüner pfeffer'], {}],
  ['zimt', 'Zimt', 'Spices, cinnamon, ground',
    ['zimt', 'zimtpulver', 'zimtstange', 'zimtstangen', 'lebkuchengewürz', 'spekulatiusgewürz', 'printengewürz', 'apfelkuchengewürz'],
    { stueck: 3 }],
  ['muskat', 'Muskat', 'Spices, nutmeg, ground', ['muskat', 'muskatnuss', 'muskatblüte', 'macis'], {}],
  ['paprikapulver', 'Paprikapulver', 'Spices, paprika',
    ['paprikapulver', 'rosenpaprika', 'paprika edelsüß', 'edelsüß', 'geräuchertes paprikapulver', 'pimentón'], {}],
  ['kreuzkuemmel', 'Kreuzkümmel', 'Spices, cumin seed', ['kreuzkümmel', 'cumin', 'kumin'], {}],
  ['kuemmel', 'Kümmel', 'Spices, caraway seed', ['kümmel'], {}],
  ['kurkuma', 'Kurkuma', 'Spices, turmeric, ground', ['kurkuma', 'gelbwurz'], {}],
  ['curry', 'Currypulver', 'Spices, curry powder', ['curry', 'currypulver', 'garam masala', 'ras el-hanout', 'ras el hanout', 'currypaste', 'fünf-gewürze-pulver'], {}],
  ['nelken', 'Nelken', 'Spices, cloves, ground', ['nelke', 'nelken', 'gewürznelken', 'nelkenpulver'], { stueck: 0.1 }],
  ['ingwerpulver', 'Ingwerpulver', 'Spices, ginger, ground', ['ingwerpulver', 'gemahlener ingwer'], {}],
  ['cayenne', 'Cayennepfeffer, Chilipulver', 'Spices, pepper, red or cayenne',
    ['cayenne', 'cayennepfeffer', 'chilipulver', 'chiliflocken', 'chilli', 'piment d\'espelette', 'sambal', 'sambal oelek', 'sambal ulek'], {}],
  ['koriandersamen', 'Koriandersamen', 'Spices, coriander seed', ['koriander', 'koriandersamen', 'gemahlener koriander'], {}],
  ['kardamom', 'Kardamom', 'Spices, cardamom', ['kardamom'], { stueck: 0.2 }],
  ['anis', 'Anis', 'Spices, anise seed', ['anis', 'anissamen', 'sternanis', 'fenchelsamen'], { stueck: 0.5 }],
  ['piment', 'Piment', 'Spices, allspice, ground', ['piment', 'pimentkörner', 'nelkenpfeffer'], { stueck: 0.1 }],
  ['getr_kraeuter', 'Getrocknete Kräuter', 'Spices, oregano, dried',
    ['oregano', 'thymian', 'majoran', 'rosmarin', 'salbei', 'bohnenkraut', 'kräuter der provence',
      'italienische kräuter', 'getrocknete kräuter', 'beifuß'], { zweig: 0.5, bund: 20 }],
  ['lorbeer', 'Lorbeer', 'Spices, bay leaf', ['lorbeer', 'lorbeerblatt', 'lorbeerblätter', 'wacholder', 'wacholderbeeren'], { stueck: 0.2, blatt: 0.2 }],
  ['senfkoerner', 'Senfkörner', 'Spices, mustard seed, ground', ['senfkörner', 'senfsaat', 'senfsamen', 'senfpulver', 'senfmehl'], {}],
  ['vanille', 'Vanille', 'Vanilla extract', ['vanille', 'vanilleschote', 'vanilleschoten', 'vanillemark', 'mark einer vanilleschote', 'mark von 1 vanilleschote', 'vanilleextrakt', 'bourbon-vanille'], { stueck: 3 }],

  // ------------------------------------------------------------ Soßen, Würzen
  ['senf', 'Senf', 'Mustard, prepared, yellow', ['senf', 'mittelscharfer senf', 'scharfer senf', 'dijonsenf', 'dijon', 'grober senf', 'süßer senf', 'mostrich'], {}],
  ['essig', 'Essig', 'Vinegar, distilled', ['essig', 'essigessenz', 'branntweinessig', 'kräuteressig', 'reisessig', 'weißer essig'], {}],
  ['weinessig', 'Weinessig', 'Vinegar, red wine', ['weinessig', 'rotweinessig', 'weißweinessig', 'sherryessig', 'estragonessig', 'himbeeressig'], {}],
  ['apfelessig', 'Apfelessig', 'Vinegar, cider', ['apfelessig', 'obstessig', 'cidre-essig'], {}],
  ['balsamico', 'Balsamico', 'Vinegar, balsamic', ['balsamico', 'balsamessig', 'aceto balsamico', 'balsamicoessig', 'balsamico-essig'], {}],
  ['sojasauce', 'Sojasauce', 'Soy sauce made from soy and wheat (shoyu)',
    ['sojasauce', 'sojasoße', 'shoyu', 'tamari', 'kecap asin', 'ketjap asin', 'fischsauce', 'fischsoße', 'nam pla', 'austernsauce', 'teriyakisauce'], {}],
  ['worcester', 'Worcestershiresauce', 'Sauce, worcestershire', ['worcestersauce', 'worcestershiresauce', 'worcestershire-sauce'], {}],
  ['ketchup', 'Ketchup', 'Catsup', ['ketchup', 'tomatenketchup', 'kecap manis', 'ketjap manis', 'bbq-sauce', 'barbecuesauce', 'chilisauce', 'sweet chili'], {}],
  ['mayonnaise', 'Mayonnaise', 'Salad dressing, mayonnaise, regular', ['mayonnaise', 'majonäse', 'remoulade', 'aioli'], {}],
  ['meerrettich', 'Meerrettich', 'Horseradish, prepared', ['meerrettich', 'kren', 'sahnemeerrettich', 'wasabi'], {}],
  ['kapern', 'Kapern', 'Capers, canned', ['kapern', 'kapernäpfel'], {}],

  // ------------------------------------------------------------ Brühen, Getränke
  ['gemuesebruehe', 'Gemüsebrühe', 'Soup, vegetable broth, ready to serve',
    ['brühe', 'gemüsebrühe', 'gemüsefond', 'instantbrühe', 'gekörnte brühe', 'bouillon', 'würfelbrühe', 'klare brühe', 'dashi'], {}],
  ['fleischbruehe', 'Fleischbrühe', 'Soup, stock, beef, home-prepared',
    ['fleischbrühe', 'rinderbrühe', 'rinderfond', 'kalbsbrühe', 'kalbsfond', 'wildfond', 'lammbrühe', 'lammfond', 'fleischfond', 'fond', 'bratenfond', 'schweinefleischfond', 'rindssuppe'], {}],
  ['huehnerbruehe', 'Hühnerbrühe', 'Soup, stock, chicken, home-prepared',
    ['hühnerbrühe', 'hühnerfond', 'geflügelbrühe', 'geflügelfond', 'entenfond', 'hühnersuppe'], {}],
  ['fischfond', 'Fischfond', 'Soup, stock, fish, home-prepared', ['fischfond', 'fischbrühe', 'fischsud'], {}],
  ['bruehwuerfel', 'Brühwürfel', 'Soup, beef broth or bouillon, powder, dry', ['brühwürfel', 'suppenwürfel', 'brühpulver', 'würfel rinderbrühe', 'würfel gemüsebrühe'], { stueck: 10, pck: 10 }],
  ['wasser', 'Wasser', 'Beverages, water, tap, drinking',
    ['wasser', 'leitungswasser', 'eiswasser', 'mineralwasser', 'sprudel', 'kochwasser', 'salzwasser'], {}],
  ['weisswein', 'Weißwein', 'Alcoholic beverage, wine, table, white',
    ['wein', 'weißwein', 'trockener weißwein', 'riesling', 'sekt', 'prosecco', 'weißherbst', 'vin santo', 'sherry', 'marsala', 'madeira', 'portwein', 'wermut', 'vermouth'], {}],
  ['rotwein', 'Rotwein', 'Alcoholic beverage, wine, table, red', ['rotwein', 'trockener rotwein', 'glühwein'], {}],
  ['bier', 'Bier', 'Alcoholic beverage, beer, regular, all', ['bier', 'dunkles bier', 'helles bier', 'weißbier', 'malzbier', 'pils', 'altbier', 'kölsch'], {}],
  ['spirituosen', 'Spirituosen', 'Alcoholic beverage, distilled, all (gin, rum, vodka, whiskey) 80 proof',
    ['rum', 'brandy', 'cognac', 'weinbrand', 'schnaps', 'obstler', 'kirschwasser', 'wodka', 'whisky', 'gin', 'likör', 'amaretto', 'grand marnier', 'calvados', 'grappa', 'inländer rum'], {}],
  ['kaffee', 'Kaffee', 'Beverages, coffee, brewed, prepared with tap water', ['kaffee', 'espresso', 'mokka', 'tee', 'schwarztee', 'grüner tee'], {}],
  ['tofu', 'Tofu', 'Tofu, raw, firm, prepared with calcium sulfate', ['tofu', 'räuchertofu', 'seidentofu'], {}],
  ['sojamilch', 'Sojadrink', 'Soymilk, original and vanilla, unfortified', ['sojamilch', 'sojadrink', 'hafermilch', 'haferdrink', 'mandelmilch', 'reismilch', 'pflanzendrink'], {}],
];
